# Part of the auth_telegram module. License LGPL-3.
import hashlib
import hmac
import logging
import secrets
import time
from datetime import timedelta

from odoo import api, fields, models, _
from odoo.exceptions import AccessDenied, UserError
try:
    from odoo.addons.auth_signup.models.res_partner import SignupError
except ImportError:
    from odoo.addons.auth_signup.models.res_users import SignupError

_logger = logging.getLogger(__name__)

# Fields signed by Telegram in the Login Widget payload
# https://core.telegram.org/widgets/login#receiving-authorization-data
TELEGRAM_AUTH_FIELDS = ('id', 'first_name', 'last_name', 'username', 'photo_url', 'auth_date')
# How long (seconds) a payload signed by Telegram is accepted after auth_date
TELEGRAM_AUTH_VALIDITY = 300
# How long (seconds) the single-use login token generated by Odoo stays valid
TELEGRAM_TOKEN_VALIDITY = 120


class ResUsers(models.Model):
    _inherit = 'res.users'

    telegram_uid = fields.Char(
        string='Telegram User ID', copy=False, index='btree_not_null',
        help="Numeric Telegram account identifier used to match this user at login. "
             "Users can find theirs with Telegram's @userinfobot, or link their "
             "account themselves at /auth/telegram/link.")
    telegram_username = fields.Char(string='Telegram Username', copy=False, readonly=True)
    telegram_token_hash = fields.Char(copy=False, readonly=True, prefetch=False, groups='base.group_system')
    telegram_token_expiration = fields.Datetime(copy=False, readonly=True, groups='base.group_system')

    _sql_constraints = [
        ('telegram_uid_unique', 'unique(telegram_uid)',
         'A user is already linked to this Telegram account.'),
    ]

    @api.model
    def _auth_telegram_enabled(self):
        ICP = self.env['ir.config_parameter'].sudo()
        return bool(ICP.get_param('auth_telegram.bot_token') and ICP.get_param('auth_telegram.bot_username'))

    @api.model
    def _auth_telegram_validate(self, params):
        """ Check the authenticity of a payload posted back by the Telegram
            Login Widget and return the validated data as a dict.
            https://core.telegram.org/widgets/login#checking-authorization
            :raise AccessDenied: forged, incomplete or expired payload
        """
        bot_token = self.env['ir.config_parameter'].sudo().get_param('auth_telegram.bot_token')
        received_hash = params.get('hash')
        if not bot_token or not received_hash or not params.get('id') or not params.get('auth_date'):
            raise AccessDenied()
        data = {k: v for k, v in params.items() if k in TELEGRAM_AUTH_FIELDS and v not in (None, '')}
        data_check_string = '\n'.join('%s=%s' % (k, data[k]) for k in sorted(data))
        secret_key = hashlib.sha256(bot_token.encode()).digest()
        expected_hash = hmac.new(secret_key, data_check_string.encode(), hashlib.sha256).hexdigest()
        if not hmac.compare_digest(expected_hash, received_hash):
            raise AccessDenied()
        try:
            auth_date = int(data['auth_date'])
        except (TypeError, ValueError):
            raise AccessDenied()
        if abs(time.time() - auth_date) > TELEGRAM_AUTH_VALIDITY:
            raise AccessDenied()
        return data

    @api.model
    def _auth_telegram_signin(self, validation):
        """ Return the user matching a validated Telegram payload together
            with a fresh single-use login token. When no user matches and
            free sign up is enabled, a new user is created on the fly.
            :raise AccessDenied: no matching user and sign up not allowed
        """
        telegram_uid = str(validation['id'])
        user = self.sudo().search([('telegram_uid', '=', telegram_uid)], limit=1)
        if not user:
            user = self.sudo()._auth_telegram_signup(validation)
        if not user or not user.active:
            raise AccessDenied()
        key = secrets.token_urlsafe(32)
        values = {
            'telegram_token_hash': hashlib.sha256(key.encode()).hexdigest(),
            'telegram_token_expiration': fields.Datetime.now() + timedelta(seconds=TELEGRAM_TOKEN_VALIDITY),
        }
        if user.telegram_username != (validation.get('username') or False):
            values['telegram_username'] = validation.get('username') or False
        user.write(values)
        return user, key

    @api.model
    def _auth_telegram_signup(self, validation):
        """ Create a new user for an unknown Telegram account, going through
            auth_signup so the b2b/b2c invitation policy and the portal
            template user are respected. """
        values = self._auth_telegram_signup_values(validation)
        try:
            self.signup(values)
        except (SignupError, UserError, ValueError) as e:
            _logger.info("Telegram signup refused for Telegram uid %s: %s", validation['id'], e)
            raise AccessDenied() from e
        return self.sudo().search([('telegram_uid', '=', str(validation['id']))], limit=1)

    @api.model
    def _auth_telegram_signup_values(self, validation):
        telegram_uid = str(validation['id'])
        name = ' '.join(p for p in (validation.get('first_name'), validation.get('last_name')) if p) \
            or validation.get('username') or _('Telegram user %s', telegram_uid)
        Users = self.sudo().with_context(active_test=False)
        login = False
        for candidate in filter(None, (validation.get('username'), 'telegram_%s' % telegram_uid)):
            if not Users.search_count([('login', '=', candidate)], limit=1):
                login = candidate
                break
        if not login:
            raise AccessDenied()
        return {
            'name': name,
            'login': login,
            'telegram_uid': telegram_uid,
            'telegram_username': validation.get('username') or False,
            'active': True,
        }

    def _check_credentials(self, credential, env):
        try:
            return super()._check_credentials(credential, env)
        except AccessDenied:
            if not (credential.get('type') == 'telegram_token' and credential.get('token')):
                raise
            if not (env or {}).get('interactive'):
                # Telegram tokens are only meant for interactive web logins
                raise
            user = self.sudo().search([('id', '=', self.env.uid)])
            if not (user and user.active and user.telegram_token_hash and user.telegram_token_expiration):
                raise
            expired = user.telegram_token_expiration < fields.Datetime.now()
            token_hash = hashlib.sha256(credential['token'].encode()).hexdigest()
            valid = hmac.compare_digest(user.telegram_token_hash, token_hash)
            # single use: consume the token whether it matched or not
            user.write({'telegram_token_hash': False, 'telegram_token_expiration': False})
            if expired or not valid:
                raise
            return {
                'uid': user.id,
                'auth_method': 'telegram',
                'mfa': 'default',
            }

    @api.model
    def _auth_telegram_link(self, uid, validation):
        """ Link a validated Telegram payload to the given user.
            :return: False when the Telegram account is already linked to
                     another user, the user record otherwise
        """
        telegram_uid = str(validation['id'])
        Users = self.sudo()
        existing = Users.with_context(active_test=False).search([('telegram_uid', '=', telegram_uid)], limit=1)
        user = Users.browse(uid)
        if existing and existing.id != user.id:
            return False
        user.write({
            'telegram_uid': telegram_uid,
            'telegram_username': validation.get('username') or False,
        })
        return user
