# Part of the auth_telegram module. License LGPL-3.
import base64
import hashlib
import hmac
import json
import logging
import secrets
import time
from datetime import timedelta
from urllib.parse import urlencode, urlparse

import requests

from odoo import api, fields, models, _
from odoo.exceptions import AccessDenied, UserError

try:
    from odoo.addons.auth_signup.models.res_partner import SignupError
except ImportError:
    from odoo.addons.auth_signup.models.res_users import SignupError

_logger = logging.getLogger(__name__)

# --- OpenID Connect flow (current Telegram login) ---------------------------
TELEGRAM_OIDC_AUTH_URL = 'https://oauth.telegram.org/auth'
TELEGRAM_OIDC_TOKEN_URL = 'https://oauth.telegram.org/token'
# phone and telegram:bot_access are optional consents: phone gives the
# verified phone number, telegram:bot_access lets the bot message the user
TELEGRAM_OIDC_SCOPE = 'openid profile phone telegram:bot_access'
TIMEOUT = 10

# --- legacy Login Widget flow (bots not switched to OIDC yet) ---------------
# https://core.telegram.org/widgets/login#receiving-authorization-data
TELEGRAM_AUTH_FIELDS = ('id', 'first_name', 'last_name', 'username', 'photo_url', 'auth_date')
TELEGRAM_AUTH_VALIDITY = 300

# How long (seconds) the single-use login token generated by Odoo stays valid
TELEGRAM_TOKEN_VALIDITY = 120


class ResUsers(models.Model):
    _inherit = 'res.users'

    telegram_uid = fields.Char(
        string='Telegram User ID', copy=False, index='btree_not_null',
        help="Numeric Telegram account identifier used to match this user at login. "
             "Users can link their account themselves at /auth/telegram/link.")
    telegram_username = fields.Char(string='Telegram Username', copy=False, readonly=True)
    telegram_phone = fields.Char(
        string='Telegram Phone', copy=False, readonly=True,
        help="Verified phone number shared by Telegram at login (requires the "
             "user's consent, OpenID Connect flow only).")
    telegram_token_hash = fields.Char(copy=False, readonly=True, prefetch=False, groups='base.group_system')
    telegram_token_expiration = fields.Datetime(copy=False, readonly=True, groups='base.group_system')

    _sql_constraints = [
        ('telegram_uid_unique', 'unique(telegram_uid)',
         'A user is already linked to this Telegram account.'),
    ]

    # ------------------------------------------------------------------
    # configuration
    # ------------------------------------------------------------------

    @api.model
    def _auth_telegram_mode(self):
        """ 'oidc' when Client ID/Secret are configured (current Telegram
            login), 'widget' when only the legacy bot username/token pair is
            configured, False when Telegram login is not configured. """
        ICP = self.env['ir.config_parameter'].sudo()
        if ICP.get_param('auth_telegram.client_id') and ICP.get_param('auth_telegram.client_secret'):
            return 'oidc'
        if ICP.get_param('auth_telegram.bot_token') and ICP.get_param('auth_telegram.bot_username'):
            return 'widget'
        return False

    @api.model
    def _auth_telegram_enabled(self):
        return bool(self._auth_telegram_mode())

    # ------------------------------------------------------------------
    # OpenID Connect flow
    # ------------------------------------------------------------------

    @api.model
    def _auth_telegram_oidc_authorize_url(self, redirect_uri, state, nonce, code_challenge):
        params = {
            'client_id': self.env['ir.config_parameter'].sudo().get_param('auth_telegram.client_id'),
            'redirect_uri': redirect_uri,
            'response_type': 'code',
            'scope': TELEGRAM_OIDC_SCOPE,
            'state': state,
            'nonce': nonce,
            'code_challenge': code_challenge,
            'code_challenge_method': 'S256',
        }
        return '%s?%s' % (TELEGRAM_OIDC_AUTH_URL, urlencode(params))

    @api.model
    def _auth_telegram_oidc_validate(self, code, code_verifier, redirect_uri, nonce):
        """ Exchange the authorization code and return the validated identity
            as {'id', 'name', 'username', 'phone'}.
            :raise AccessDenied: exchange refused or inconsistent id_token
        """
        ICP = self.env['ir.config_parameter'].sudo()
        client_id = ICP.get_param('auth_telegram.client_id')
        client_secret = ICP.get_param('auth_telegram.client_secret')
        if not client_id or not client_secret or not code:
            raise AccessDenied()
        try:
            response = requests.post(TELEGRAM_OIDC_TOKEN_URL, data={
                'grant_type': 'authorization_code',
                'code': code,
                'redirect_uri': redirect_uri,
                'code_verifier': code_verifier,
            }, auth=(client_id, client_secret), timeout=TIMEOUT)
        except requests.RequestException:
            _logger.warning("Telegram OIDC: token endpoint unreachable", exc_info=True)
            raise AccessDenied()
        if not response.ok:
            _logger.info("Telegram OIDC: code exchange refused: %s", response.text[:300])
            raise AccessDenied()
        try:
            id_token = response.json().get('id_token')
        except ValueError:
            raise AccessDenied()
        claims = self._auth_telegram_jwt_payload(id_token)
        # the id_token was just received from the issuer over TLS with client
        # authentication, which stands in for signature verification; the
        # standard claims are still checked
        issuer_host = urlparse(claims.get('iss') or '').hostname or ''
        if issuer_host != 'oauth.telegram.org' and not issuer_host.endswith('.telegram.org'):
            raise AccessDenied()
        audience = claims.get('aud')
        audience = audience if isinstance(audience, list) else [audience]
        if client_id not in [str(a) for a in audience]:
            raise AccessDenied()
        try:
            if int(claims.get('exp', 0)) < time.time():
                raise AccessDenied()
        except (TypeError, ValueError):
            raise AccessDenied()
        token_nonce = claims.get('nonce')
        if nonce and token_nonce and not hmac.compare_digest(str(token_nonce), nonce):
            raise AccessDenied()
        if not claims.get('sub'):
            raise AccessDenied()
        return {
            'id': str(claims['sub']),
            'name': claims.get('name') or False,
            'username': claims.get('preferred_username') or False,
            'phone': claims.get('phone_number') or False,
        }

    @api.model
    def _auth_telegram_jwt_payload(self, token):
        try:
            payload = token.split('.')[1]
            payload += '=' * (-len(payload) % 4)
            return json.loads(base64.urlsafe_b64decode(payload.encode()))
        except Exception:
            raise AccessDenied()

    # ------------------------------------------------------------------
    # legacy Login Widget flow
    # ------------------------------------------------------------------

    @api.model
    def _auth_telegram_validate(self, params):
        """ Check the authenticity of a payload posted back by the legacy
            Telegram Login Widget and return the validated identity as
            {'id', 'name', 'username', 'phone'}.
            :raise AccessDenied: forged, incomplete or expired payload
        """
        bot_token = self.env['ir.config_parameter'].sudo().get_param('auth_telegram.bot_token')
        received_hash = params.get('hash')
        if not bot_token or not received_hash or not params.get('id') or not params.get('auth_date'):
            raise AccessDenied()
        data = {k: v for k, v in params.items() if k in TELEGRAM_AUTH_FIELDS and v not in (None, '')}
        data_check_string = '\n'.join('%s=%s' % (k, data[k]) for k in sorted(data))
        secret_key = hashlib.sha256(bot_token.encode()).digest()
        expected_hash = hmac.new(secret_key, data_check_string.encode(), hashlib.sha256).hexdigest()
        if not hmac.compare_digest(expected_hash, received_hash):
            raise AccessDenied()
        try:
            auth_date = int(data['auth_date'])
        except (TypeError, ValueError):
            raise AccessDenied()
        if abs(time.time() - auth_date) > TELEGRAM_AUTH_VALIDITY:
            raise AccessDenied()
        name = ' '.join(p for p in (data.get('first_name'), data.get('last_name')) if p)
        return {
            'id': str(data['id']),
            'name': name or False,
            'username': data.get('username') or False,
            'phone': False,
        }

    # ------------------------------------------------------------------
    # sign in / sign up / link (flow independent)
    # ------------------------------------------------------------------

    @api.model
    def _auth_telegram_signin(self, validation):
        """ Return the user matching a validated Telegram identity together
            with a fresh single-use login token. When no user matches and
            free sign up is enabled, a new user is created on the fly.
            :raise AccessDenied: no matching user and sign up not allowed
        """
        telegram_uid = str(validation['id'])
        user = self.sudo().search([('telegram_uid', '=', telegram_uid)], limit=1)
        if not user:
            user = self.sudo()._auth_telegram_signup(validation)
        if not user or not user.active:
            raise AccessDenied()
        key = secrets.token_urlsafe(32)
        values = {
            'telegram_token_hash': hashlib.sha256(key.encode()).hexdigest(),
            'telegram_token_expiration': fields.Datetime.now() + timedelta(seconds=TELEGRAM_TOKEN_VALIDITY),
        }
        if user.telegram_username != (validation.get('username') or False):
            values['telegram_username'] = validation.get('username') or False
        if validation.get('phone') and user.telegram_phone != validation['phone']:
            values['telegram_phone'] = validation['phone']
        user.write(values)
        if validation.get('phone') and not user.partner_id.phone:
            user.partner_id.phone = validation['phone']
        return user, key

    @api.model
    def _auth_telegram_signup(self, validation):
        """ Create a new user for an unknown Telegram account, going through
            auth_signup so the b2b/b2c invitation policy and the portal
            template user are respected. """
        values = self._auth_telegram_signup_values(validation)
        try:
            self.signup(values)
        except (SignupError, UserError, ValueError) as e:
            _logger.info("Telegram signup refused for Telegram uid %s: %s", validation['id'], e)
            raise AccessDenied() from e
        return self.sudo().search([('telegram_uid', '=', str(validation['id']))], limit=1)

    @api.model
    def _auth_telegram_signup_values(self, validation):
        telegram_uid = str(validation['id'])
        name = validation.get('name') or validation.get('username') \
            or _('Telegram user %s', telegram_uid)
        Users = self.sudo().with_context(active_test=False)
        login = False
        for candidate in filter(None, (validation.get('username'), 'telegram_%s' % telegram_uid)):
            if not Users.search_count([('login', '=', candidate)], limit=1):
                login = candidate
                break
        if not login:
            raise AccessDenied()
        values = {
            'name': name,
            'login': login,
            'telegram_uid': telegram_uid,
            'telegram_username': validation.get('username') or False,
            'telegram_phone': validation.get('phone') or False,
            'active': True,
        }
        if validation.get('phone'):
            values['phone'] = validation['phone']
        return values

    @api.model
    def _auth_telegram_link(self, uid, validation):
        """ Link a validated Telegram identity to the given user.
            :return: False when the Telegram account is already linked to
                     another user, the user record otherwise
        """
        telegram_uid = str(validation['id'])
        Users = self.sudo()
        existing = Users.with_context(active_test=False).search([('telegram_uid', '=', telegram_uid)], limit=1)
        user = Users.browse(uid)
        if existing and existing.id != user.id:
            return False
        user.write({
            'telegram_uid': telegram_uid,
            'telegram_username': validation.get('username') or False,
            'telegram_phone': validation.get('phone') or False,
        })
        if validation.get('phone') and not user.partner_id.phone:
            user.partner_id.phone = validation['phone']
        return user

    # ------------------------------------------------------------------
    # authentication
    # ------------------------------------------------------------------

    def _check_credentials(self, credential, env):
        try:
            return super()._check_credentials(credential, env)
        except AccessDenied:
            if not (credential.get('type') == 'telegram_token' and credential.get('token')):
                raise
            if not (env or {}).get('interactive'):
                # Telegram tokens are only meant for interactive web logins
                raise
            user = self.sudo().search([('id', '=', self.env.uid)])
            if not (user and user.active and user.telegram_token_hash and user.telegram_token_expiration):
                raise
            expired = user.telegram_token_expiration < fields.Datetime.now()
            token_hash = hashlib.sha256(credential['token'].encode()).hexdigest()
            valid = hmac.compare_digest(user.telegram_token_hash, token_hash)
            # single use: consume the token whether it matched or not
            user.write({'telegram_token_hash': False, 'telegram_token_expiration': False})
            if expired or not valid:
                raise
            return {
                'uid': user.id,
                'auth_method': 'telegram',
                'mfa': 'default',
            }
